# Generated by Django 5.2.1 on 2025-09-29 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FurhubApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardingpolicy',
            name='pet_boarding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_policy', to='FurhubApi.petboarding'),
        ),
        migrations.AlterField(
            model_name='operationalhours',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_hours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='walkerrate',
            name='pet_walker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='walker_rate', serialize=False, to='FurhubApi.petwalker'),
        ),
    ]
