# Generated by Django 5.2.1 on 2025-06-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FurhubApi', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user_roles',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='unique_user_role'),
        ),
    ]
