# Generated by Django 5.2.1 on 2025-09-07 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FurhubApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='capture_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paypal_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transactionlogs',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transactionlogs',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal')], max_length=50),
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('payout_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('unclaimed', 'Unclaimed')], default='pending', max_length=20)),
                ('paypal_batch_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payout_item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout', to='FurhubApi.booking')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='FurhubApi.providerservice')),
            ],
            options={
                'db_table': 'payout',
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('ledger_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('sale', 'Sale'), ('payout', 'Payout'), ('refunded', 'Refunded')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('running_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FurhubApi.booking')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FurhubApi.payment')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='FurhubApi.providerservice')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FurhubApi.payout')),
            ],
            options={
                'db_table': 'provider_ledger',
            },
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_earning', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='FurhubApi.providerservice')),
            ],
            options={
                'db_table': 'user_balance',
            },
        ),
    ]
