# Generated by Django 5.2.1 on 2025-09-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FurhubApi', '0002_alter_boardingpolicy_pet_boarding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalhours',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operationalhours',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
