# Generated by Django 5.2.1 on 2025-09-22 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FurhubApi', '0002_payment_capture_id_payment_currency_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petboarding',
            name='status',
        ),
        migrations.RemoveField(
            model_name='petwalker',
            name='status',
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='label',
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='category',
            field=models.CharField(choices=[('profile_picture', 'Profile Picture'), ('community_post', 'Community Post')], max_length=50),
        ),
        migrations.CreateModel(
            name='ProviderApplication',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('provider_type', models.CharField(choices=[('walker', 'Pet Walker'), ('boarding', 'Pet Boarding')], max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('facility_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FurhubApi.location')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'provider_application',
            },
        ),
        migrations.CreateModel(
            name='ProviderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('valid_id', 'Valid ID'), ('selfie_with_id', 'Selfie with ID')], max_length=50)),
                ('file', models.FileField(upload_to='provider_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='FurhubApi.providerapplication')),
            ],
            options={
                'db_table': 'provider_documents',
            },
        ),
    ]
