# Generated by Django 5.2.1 on 2025-06-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FurhubApi', '0003_users_code_expiry_users_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petboarding',
            name='availability',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='petboarding',
            name='hotel_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='petowner',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petowner',
            name='emergency_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='petwalker',
            name='availability',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
