# Generated by Django 5.2.1 on 2025-09-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FurhubApi', '0003_alter_operationalhours_close_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration_unit',
            field=models.CharField(blank=True, choices=[('hour', 'Hour'), ('day', 'Day'), ('week', 'Week')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='duration_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
