# Generated by Django 5.2.1 on 2025-09-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FurhubApi', '0003_remove_petboarding_status_remove_petwalker_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
