# Generated by Django 5.2.1 on 2025-09-22 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FurhubApi', '0004_alter_providerapplication_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='providerdocument',
            old_name='file',
            new_name='image',
        ),
    ]
