# Generated by Django 5.2.1 on 2025-06-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FurhubApi', '0005_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='petboarding',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='petwalker',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
