# Generated by Django 5.2.1 on 2025-09-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FurhubApi', '0006_providerdocument_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerapplication',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerapplication',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerapplication',
            name='registration_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='providerapplication',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
