# Generated by Django 5.2.1 on 2025-06-30 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FurhubApi', '0007_service'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='service',
            table='service',
        ),
        migrations.CreateModel(
            name='ProviderService',
            fields=[
                ('providerService_id', models.AutoField(primary_key=True, serialize=False)),
                ('provider_type', models.CharField(choices=[('walker', 'Pet Walker'), ('boarding', 'Pet Boarding')], max_length=15)),
                ('provider_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FurhubApi.service')),
            ],
            options={
                'db_table': 'provider_service',
            },
        ),
    ]
