# Generated by Django 5.2.1 on 2025-06-30 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FurhubApi', '0008_alter_service_table_providerservice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='providerservice',
            unique_together={('service', 'provider', 'provider_type')},
        ),
    ]
