# Generated by Django 5.2.1 on 2025-07-30 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FurhubApi', '0009_alter_providerservice_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_id',
            new_name='id',
        ),
    ]
