// services/walkers/cebuWalkers.ts

export const cebuWalkers = [
  {
    id: "w1",
    name: "Rep. Roman Romulo",
    province: "Cebu",
    city: "Cebu City",
    barangay: "Lahug",
    street: "Escario St.",
    pricePerHour: 150,
    servicePrices: { Walking: 50, Feeding: 70, Grooming: 100 },
    image: "https://randomuser.me/api/portraits/men/32.jpg",
    description: "Friendly dog walker with 5 years of experience taking care of pets in Cebu City.",
    services: ["Walking", "Feeding", "Grooming"],
    lat: 10.3269,
    long: 123.9059,
    reviews: 85,
    rating: 4.0,
  },
  {
    id: "w2",
    name: "Rep. Arjo Atayde",
    province: "Cebu",
    city: "Mandaue City",
    barangay: "Banilad",
    street: "A.S. Fortuna St.",
    pricePerHour: 180,
    servicePrices: { Walking: 60, Feeding: 80, Training: 120 },
    image: "https://randomuser.me/api/portraits/women/45.jpg",
    description: "Passionate pet lover providing trustworthy dog walking services.",
    services: ["Walking", "Exercise", "Training"],
    lat: 10.3414,
    long: 123.9362,
    reviews: 120,
    rating: 4.5,
  },
  {
    id: "w3",
    name: "Luis Gonzales",
    province: "Cebu",
    city: "Lapu-Lapu City",
    barangay: "Pusok",
    street: "Mactan Avenue",
    pricePerHour: 170,
    servicePrices: { Walking: 50, Feeding: 70 },
    image: "https://randomuser.me/api/portraits/men/44.jpg",
    description: "Reliable pet walker near Mactan Airport, loves spending time with dogs.",
    services: ["Walking", "Pet Playtime", "Feeding"],
    lat: 10.3109,
    long: 123.9495,
    reviews: 90,
    rating: 4.2,
  },
  {
    id: "w4",
    name: "Clara Lim",
    province: "Cebu",
    city: "Cebu City",
    barangay: "Banilad",
    street: "Gov. M. Cuenco Ave.",
    pricePerHour: 140,
    servicePrices: { Walking: 40, Feeding: 60 },
    image: "https://randomuser.me/api/portraits/women/30.jpg",
    description: "Affordable and caring dog walker for busy pet owners.",
    services: ["Walking", "Feeding"],
    lat: 10.3300,
    long: 123.9050,
    reviews: 60,
    rating: 3.9,
  },
  {
    id: "w5",
    name: "James Dela Cruz",
    province: "Cebu",
    city: "Mandaue City",
    barangay: "Guadalupe",
    street: "Plaridel St.",
    pricePerHour: 200,
    servicePrices: { Walking: 70, Feeding: 80, Training: 120 },
    image: "https://randomuser.me/api/portraits/men/50.jpg",
    description: "Premium walker providing personalized care for your pets.",
    services: ["Walking", "Feeding", "Training"],
    lat: 10.3370,
    long: 123.9380,
    reviews: 75,
    rating: 4.6,
  },
  {
    id: "w6",
    name: "Sofia Tan",
    province: "Cebu",
    city: "Cebu City",
    barangay: "Talamban",
    street: "Gov. M. Cuenco Ave.",
    pricePerHour: 160,
    servicePrices: { Walking: 50, Feeding: 60 },
    image: "https://randomuser.me/api/portraits/women/52.jpg",
    description: "Friendly walker who loves pets and ensures they are happy and safe.",
    services: ["Walking", "Pet Playtime"],
    lat: 10.3450,
    long: 123.9100,
    reviews: 50,
    rating: 4.1,
  },
];
