// services/walkers/cebuWalkers.ts

export const cebuWalkers = [
  {
    id: "w1",
    name: "Rep. Roman Romulo",
    province: "Cebu",
    city: "Cebu City",
    barangay: "Lahug",
    street: "Escario St.",
    pricePerHour: 150,
    image: "https://randomuser.me/api/portraits/men/32.jpg",
    description:
      "Friendly dog walker with 5 years of experience taking care of pets in Cebu City.",
    lat: 10.3269,
    long: 123.9059,
    reviews: 85,
    rating: 4.0,
    routes: [
      { name: "Lahug IT Park Loop"},
      { name: "Escario–Ayala Walk"},
    ],
  },
  {
    id: "w2",
    name: "Rep. Arjo Atayde",
    province: "Cebu",
    city: "Mandaue City",
    barangay: "Banilad",
    street: "A.S. Fortuna St.",
    pricePerHour: 180,
    image: "https://randomuser.me/api/portraits/women/45.jpg",
    description: "Passionate pet lover providing trustworthy dog walking services.",
    lat: 10.3414,
    long: 123.9362,
    reviews: 120,
    rating: 4.5,
    routes: [
      { name: "Banilad Town Center Loop"},
      { name: "A.S. Fortuna Route"},
    ],
  },
  {
    id: "w3",
    name: "Luis Gonzales",
    province: "Cebu",
    city: "Lapu-Lapu City",
    barangay: "Pusok",
    street: "Mactan Avenue",
    pricePerHour: 170,
    image: "https://randomuser.me/api/portraits/men/44.jpg",
    description:
      "Reliable pet walker near Mactan Airport, loves spending time with dogs.",
    lat: 10.3109,
    long: 123.9495,
    reviews: 90,
    rating: 4.2,
    routes: [
      { name: "Mactan Airport Park Walk"},
      { name: "Pusok Barangay Route"},
    ],
  },
  {
    id: "w4",
    name: "Clara Lim",
    province: "Cebu",
    city: "Cebu City",
    barangay: "Banilad",
    street: "Gov. M. Cuenco Ave.",
    pricePerHour: 140,
    image: "https://randomuser.me/api/portraits/women/30.jpg",
    description: "Affordable and caring dog walker for busy pet owners.",
    lat: 10.3300,
    long: 123.9050,
    reviews: 60,
    rating: 3.9,
    routes: [
      { name: "Banilad Gov. Cuenco Route"},
      { name: "Gaisano Country Mall Loop"},
    ],
  },
  {
    id: "w5",
    name: "James Dela Cruz",
    province: "Cebu",
    city: "Mandaue City",
    barangay: "Guadalupe",
    street: "Plaridel St.",
    pricePerHour: 200,
    image: "https://randomuser.me/api/portraits/men/50.jpg",
    description: "Premium walker providing personalized care for your pets.",
    lat: 10.3370,
    long: 123.9380,
    reviews: 75,
    rating: 4.6,
    routes: [
      { name: "Plaridel St. Walk"},
      { name: "Mandaue Plaza Route"},
    ],
  },
  {
    id: "w6",
    name: "Sofia Tan",
    province: "Cebu",
    city: "Cebu City",
    barangay: "Talamban",
    street: "Gov. M. Cuenco Ave.",
    pricePerHour: 160,
    image: "https://randomuser.me/api/portraits/women/52.jpg",
    description: "Friendly walker who loves pets and ensures they are happy and safe.",
    lat: 10.3450,
    long: 123.9100,
    reviews: 50,
    rating: 4.1,
    routes: [
      { name: "Talamban Riverside Walk"},
      { name: "Cuenco Ave. Park Route"},
    ],
  },
];
